[package]
name = "lon"
version = "0.8.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
log = "0.4.29"
stderrlog = "0.6.0"
clap = { version = "4.6.1", features = ["derive"] }
serde = { version = "1.0.228", features = [ "derive" ] }
serde_json = "1.0.149"
sha2 = "0.11.0"
tempfile = "3.27.0"
reqwest = { version = "0.13", default-features = false, features = ["blocking","http2","default-tls","json"] }
nix-compat = { git = "https://git.snix.dev/snix/snix", rev = "e952b5ae99242baed8f6ffa1b98aa80f4f02911e", default-features = false, features = ["serde"] }
regex = "1.12.3"
serde_qs = "1.1.1"

[dev-dependencies]
expect-test = "1.5.1"
assert_cmd = "2.2.1"
tempfile = "3.27.0"
indoc = "2.0.7"

[build-dependencies]
sha2 = "0.11.0"

[profile.release]
opt-level = "s"
panic = "abort"
lto = true
strip = true

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny" }
pedantic = { level = "deny" }
unwrap_used = { level = "deny", priority = 1 }
needless_raw_string_hashes = { level = "allow", priority = 1 }
module_name_repetitions = { level = "allow", priority = 1 }
missing_errors_doc = { level = "allow", priority = 1 }
