# SPDX-FileCopyrightText: 2026 lon contributors
#
# SPDX-License-Identifier: MIT

# Generated by lon. Do not modify!
let
  lock = builtins.fromJSON (builtins.readFile ./lon.lock);

  overrideFromEnv =
    name: path:
    let
      replacement = builtins.getEnv "LON_OVERRIDE_${name}";
    in
    if replacement == "" then
      path
    else if builtins.substring 0 1 replacement == "/" then
      /. + replacement
    else
      /. + builtins.getEnv "PWD" + "/${replacement}";

  fetchSource =
    args@{ fetchType, ... }:
    if fetchType == "git" then
      fetchGit {
        url = args.url;
        ref = args.branch;
        rev = args.revision;
        narHash = args.hash;
        submodules = args.submodules;
        lastModified = args.lastModified;
        shallow = true;
      }
    else if fetchType == "tarball" then
      fetchTarball {
        url = args.url;
        sha256 = args.hash;
      }
    else
      throw "Unsupported source type ${fetchType}";
in
builtins.mapAttrs (name: args: overrideFromEnv name (fetchSource args)) lock.sources
